discourse_peertube_embed:
  peertube_embed_enabled:
    default: false
    client: true
  peertube_embed_instances:
    type: host_list
    default: ""
    client: true
  peertube_embed_click_to_play:
    default: true
    client: true
  peertube_embed_theater_mode:
    default: true
    client: true
  peertube_embed_composer_button:
    default: true
    client: true
  peertube_embed_topic_list_thumbnails:
    default: true
    client: true
  peertube_embed_videos_page:
    default: true
    client: true
  peertube_embed_home_instance:
    default: ""
    client: true
  peertube_embed_videos_default_tab:
    type: enum
    default: all
    enum: "DiscoursePeertube::DefaultTabSetting"
    client: true
  peertube_embed_live_refresh_seconds:
    default: 60
    min: 60
    max: 600
    client: true
  peertube_embed_sync_event_livestream_hosts:
    default: true
  peertube_embed_upload_enabled:
    default: false
    client: true
  peertube_embed_upload_username:
    default: ""
  peertube_embed_upload_password:
    default: ""
    secret: true
  peertube_embed_upload_channel:
    default: ""
  peertube_embed_upload_category_channels:
    type: list
    list_type: simple
    default: ""
  peertube_embed_upload_allowed_groups:
    type: group_list
    list_type: compact
    default: "1|2|12"
    allow_any: false
  peertube_embed_upload_max_size_mb:
    default: 0
    min: 0
    max: 1048576
    client: true
